sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
script:
  - pip install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse
  - tox
services:
  - redis-server
